CREATE DATABASE ALUGUEIS;
GO

USE ALUGUEIS;
GO



CREATE TABLE CLIENTE(
	idCliente INT PRIMARY KEY IDENTITY(1,1),
		nomeCliente VARCHAR(20)
);
GO

CREATE TABLE MARCA(
	idMarca TINYINT PRIMARY KEY IDENTITY(1,1),
		nomeMarca VARCHAR(20),
);
GO

CREATE TABLE MODELO(
	idModelo TINYINT PRIMARY KEY IDENTITY(1,1),
	idMarca TINYINT FOREIGN KEY REFERENCES MARCA(idMarca),
		nomeModelo VARCHAR(20)
);
GO

CREATE TABLE ALUGUEL(
	idAluguel INT PRIMARY KEY IDENTITY(1,1),
	idCliente INT FOREIGN KEY REFERENCES CLIENTE(idCliente),
	idVeiculo TINYINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
		dataRetirada VARCHAR(10),
		dataDevolucao VARCHAR(10),
);
GO

CREATE TABLE VEICULO(
	idVeiculo TINYINT PRIMARY KEY IDENTITY(1,1),
	idModelo TINYINT FOREIGN KEY REFERENCES MODELO(idModelo),
		placa VARCHAR(8)
);
GO

CREATE TABLE EMPRESA(
	idEmpresa TINYINT PRIMARY KEY IDENTITY(1,1),
		nomeEmpresa VARCHAR(20)
		
);
GO
