CREATE DATABASE REGISTROS;
GO

USE REGISTROS;
GO

CREATE TABLE TIPO(
	idTipo TINYINT PRIMARY KEY IDENTITY(1,1),
		nomeTipo VARCHAR(20)
		
);
GO

CREATE TABLE RACA(
	idRaca TINYINT PRIMARY KEY IDENTITY(1,1),
	idTipo TINYINT FOREIGN KEY REFERENCES TIPO(idTipo),
		nomeRaca VARCHAR(25)

);
GO

CREATE TABLE DONO(
	idDono TINYINT PRIMARY KEY IDENTITY(1,1),
		nomeDono VARCHAR(20)
		
);
GO

CREATE TABLE PET(
	idPet  INT PRIMARY KEY IDENTITY(1,1),
	idRaca TINYINT FOREIGN KEY REFERENCES RACA(idRaca),
	nomePet VARCHAR(20)
	
);
GO

CREATE TABLE ATENDIMENTO(
	idAtendimento INT PRIMARY KEY IDENTITY(1,1),
	idPet INT FOREIGN KEY REFERENCES PET(idPet),
	idVeterinario TINYINT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
		descricaoConsulta VARCHAR(20),
		dataConsulta VARCHAR(20)
);
GO

CREATE TABLE VETERINARIO(
	idVeterinario TINYINT PRIMARY KEY IDENTITY (1,1),
		nomeVeterinario VARCHAR(20)
);
GO

CREATE TABLE CLINICA(
	idClinica TINYINT PRIMARY KEY IDENTITY(1,1),
		nomeClinica VARCHAR (20)
);
GO