SELECT * FROM CLINICA
SELECT * FROM TIPO
SELECT * FROM DONO
SELECT * FROM PET
SELECT * FROM RACA
SELECT * FROM VETERINARIO
SELECT * FROM ATENDIMENTO

SELECT nomeClinica, nomeVeterinario FROM CLINICA
INNER JOIN VETERINARIO
ON CLINICA.idClinica = VETERINARIO.idVeterinario
GO

SELECT nomeRaca FROM RACA
WHERE nomeRaca LIKE 's%'

SELECT nomeRaca FROM RACA
WHERE nomeRaca LIKE '%o'

SELECT nomePet, nomeDono FROM PET
INNER JOIN DONO
ON PET.idPet = DONO.idDono

SELECT nomeVeterinario, nomePet, nomeRaca, nomeTipo, nomeDono, nomeClinica FROM ATENDIMENTO
INNER JOIN VETERINARIO
ON ATENDIMENTO.idAtendimento = VETERINARIO.idVeterinario
INNER JOIN PET
ON ATENDIMENTO.idAtendimento = PET.idPet
INNER JOIN RACA
ON ATENDIMENTO.idAtendimento = RACA.idRaca
INNER JOIN TIPO
ON ATENDIMENTO.idAtendimento = TIPO.idTipo
INNER JOIN DONO
ON ATENDIMENTO.idAtendimento = DONO.idDono
INNER JOIN CLINICA
ON ATENDIMENTO.idAtendimento = CLINICA.idClinica